### ISSUE TITLE
NodeJs > 8 makes the command fail

### ISSUE THREAD

**Issue by defvs** [TooTallNate/RetroPie-profiles-facebook-login#2]
Looks like --harmony-async-await is now rejected starting NodeJs 8

**Comment by defvs** [comment]
#1 tries to fix it, but sadly not backward compatible (< 7.6 i think)

**Comment by defvs** [comment]
Works fine on NodeJS 8.9.0 for me with the fix

**Comment by TooTallNate** [comment]
Fixed by #1. Thanks @cab13140!
